APP_TITLES = {
    #Realme system apps
     'com.android.internal.systemui.navbar.threebutton':'3 Button Navigation Bar',
    'com.google.android.adservices.api':'Ad privacy',
    'com.qualcomm.qti.gpudrivers.lahaina.api30':'Adreno Graphics Drivers',
    'com.rongcard.eidapi':'aidlserverdemo',
    'com.oplus.aiunit':'AIUnit',
    'com.oplus.aod':'Always-on Display',
    'com.google.android.marvin.talkback':'Android Accessibility Suite',
    'com.google.android.projection.gearhead':'Android Auto',
    'com.android.egg':'Android S Easter Egg',
    'com.google.android.ext.services':'Android Service Library',
    'com.google.android.setupwizard':'Android Setup',
    'com.google.android.ext.shared':'Android Shared Library',
    'android':'Android System',
    'oplus':'Android System',
    'com.google.android.as':'Android System Intelligence',
    'com.google.android.webview':'Android System WebView',
    'com.oplus.multiapp':'App Cloner',
    'com.oplus.cosa':'App Enhancement Services',
    'com.applovin.array.apphub.vincere':'AppHub',
    'com.heytap.market':'App Picks',
    'com.oplus.appplatform':'App Service',
    'com.fido.fido2client':'asmsdk',
    'com.google.android.apps.googleassistant ':'Assisstant',
    'com.coloros.backuprestore':'Clone Phone',
    'com.oplus.consumerIRApp':'IR Remote',
    'com.fitbit.FitbitMobile':'Fitbit',
    'com.heytap.browser':'Internet',
    'com.realmecomm.app':'Community',
    '':'',
    '':'',
    '':'',





    # OPPO/Realme/ColorOS Apps
    'com.oppo.market': 'App Market',
    'com.heytap.gamecenter': 'Game Center',
    'com.heytap.cloud': 'HeyTap Cloud',
    'com.redteamobile.roaming': 'ORoaming',
    'com.opos.cs': 'Hot Apps',
    'com.heytap.synergy': 'HeySynergy',
    'com.heytap.pictorial': 'Lock Screen Magazine',
    'com.heytap.music': 'Music',
    'com.oppo.operationManual': 'User Guide',
    'com.coloros.video': 'Video',
    'com.realme.link': 'Realme Link',
    'com.realmepay.payments': 'Realme PaySa',
    'com.realmestore.app': 'Realme Store',
    'com.coloros.soundrecorder': 'Realme Recorder',
    'com.coloros.weather2': 'Weather',
    'com.coloros.weather.service': 'Weather Service',
    'com.netflix.mediaclient':'Netflix',
    'com.oppo.quicksearchbox':'Global Search',
   
    # Google Apps
    'com.google.android.googlequicksearchbox': 'Google',
    'com.google.android.browser': 'Chrome',
    'com.google.android.apps.maps': 'Google Maps',
    'com.google.android.apps.docs': 'Google Drive',
    'com.google.android.apps.photos': 'Photos',
    'com.google.android.calendar': 'Calendar',
    'com.google.android.keep': 'Keep',
    'com.google.android.apps.translate': 'Translate',
    'com.google.android.apps.newsstand': 'Google News',
    'com.google.android.gm': 'Gmail',
    'com.google.android.youtube': 'YouTube',
    'com.google.android.apps.youtube.music': 'YouTube Music',
    'com.android.vending': 'Play Store',
    'com.google.android.apps.googleassistant': 'Google Assistant',
    'com.google.android.apps.tachyon': 'Google Meet',
    'com.google.android.apps.meetings': 'Meet',
    'com.google.android.apps.walletnfcrel': 'Google Pay',
    'com.google.android.apps.nbu.paisa.user': 'Google Pay',
    'com.google.android.apps.sheets': 'Sheets',
    'com.google.android.apps.slides': 'Slides',
    'com.google.android.apps.classroom': 'Classroom',
    'com.google.earth': 'Google Earth',
    'com.google.android.apps.maps.lite': 'Maps Go',
    'com.google.android.apps.filego': 'Files',
    'com.google.android.apps.subscriptions.red': 'Google One',
    'com.google.android.apps.adm':'Google Find My Device',
    'com.google.android.apps.walletnfcrel':'Google Wallet',
    'com.google.android.apps.chromecast.app':'Google Home',
    'com.google.android.videos':'Google Tv',
 

    #other apps
    'com.crrepa.band.dafit': 'Da Fit',
    'com.intel.mde': 'Intel® Unison™',
    'com.amazon.avod.thirdpartyclient': 'Amazon Prime Video',
    'in.amazon.mShop.android.shopping': 'Amazon',
    'com.mxtech.videoplayer.ad':'MX Player',
    'com.digilocker.android':'DigiLocker',
    'com.duckduckgo.mobile.android':'DuckDuckGo',
    'com.flipkart.android':'Flipkart',
	'com.facebook.katana':'Facebook',
	'com.instagram.android':'Instagram',
	'com.twitter.android':'Twitter',
	'com.ss.android.ugc.aweme':'TikTok',
	'com.whatsapp':'WhatsApp',
	'com.snapchat.android':'Snapchat',
	'com.linkedin.android':'LinkedIn',
	'com.pinterest':'Pinterest',
	'com.reddit.frontpage':'Reddit',
	'com.tumblr':'Tumblr',
	'com.discord':'Discord',
	'org.telegram.messenger':'Telegram',
	'org.thoughtcrime.securesms':'Signal',
    'com.microsoft.appmanager':'Link to Windows',
    'com.phonepe.app':'PhonePe',
    'com.coloros.backuprestore':'OPPO Clone Phone',
    'com.sbi.lotusintouch':'YONO SBI',
    'com.myntra.android':'Myntra',
    'com.oneplus.brickmode':'Zen Space',
    'com.csdroid.pkg':'Package Names',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    

} 
